;;; Add directory with setup files to load-path.
(add-to-list 'load-path (concat user-emacs-directory "my-settings"))

(require 'setup-load-path)
(require 'setup-appearance)
(require 'setup-dash)
(require 'setup-defuns)
(require 'setup-whitespace)
(require 'setup-scrolling)
(require 'setup-dired-mode)
(require 'setup-org-mode)
(require 'setup-proced-mode)
(require 'setup-expand-region-mode)
(require 'setup-multiple-cursors-mode)
(require 'setup-undo-tree-mode)
(require 'setup-ace-jump-mode)
(require 'setup-git-modes)
(require 'setup-paredit-mode)
(require 'setup-ido-mode)
(require 'setup-auto-saving)
(require 'setup-ediff)
(require 'setup-ess-mode)
(require 'setup-tex-modes)
(require 'setup-haskell-mode)
(require 'setup-indentation)
(require 'setup-fonts)
(require 'setup-misc)
(require 'setup-magit)
(require 'setup-slime)
(require 'setup-keybindings)

;;; Load aliases.
(let ((alias-file "~/.emacs.d/.alias.el"))
  (when (file-readable-p alias-file)
    (load alias-file)))
